## Import statements

In [9]:
import json
import pandas as pd
import zipfile
from IPython.display import display

## Data preparation

### 1. Weather data

In [10]:
with open("weather/2024-01-01.json") as f:
    data = json.load(f)

# Flatten JSON
weather = pd.json_normalize(data)

display(weather)

,type,id,geometry.coordinates,geometry.type,properties.calculatedAt,properties.created,properties.from,properties.parameterId,properties.qcStatus,properties.stationId,properties.timeResolution,properties.to,properties.validity,properties.value,properties.noValuesInCalculation,properties.cloudCoverMethod,properties.extremeOccurence.type,properties.extremeOccurence.value
0,Feature,001f83a3-5ef7-3106-86bb-ddbdef4142bd,"[12.4121, 55.8764]",Point,2024-01-03T03:03:13.163000+00:00,2024-01-03T14:14:34.594034+00:00,2024-01-01T23:00:00+00:00,mean_relative_hum,manual,06188,hour,2024-01-02T00:00:00+00:00,True,93.5,NaN,NaN,NaN,NaN
1,Feature,006c4afa-2207-b54a-75b3-b9af8d74fa13,"[9.1674, 55.7379]",Point,2024-01-04T08:42:19.106000+00:00,2024-01-04T08:42:20.417145+00:00,2024-01-02T00:00:00.001000+01:00,max_wind_speed_3sec,manual,06104,day,2024-01-03T00:00:00+01:00,True,21.6,24.0,NaN,NaN,NaN
2,Feature,00743083-2830-f046-5440-bfa86b3bf1d7,"[9.5067, 56.7558]",Point,2024-01-03T03:03:14.520000+00:00,2024-01-03T14:14:54.919106+00:00,2024-01-01T23:00:00+00:00,max_wind_speed_10min,manual,06065,hour,2024-01-02T00:00:00+00:00,True,8.5,NaN,NaN,NaN,NaN
3,Feature,00952cb4-3797-4392-5608-d4ccf1ab01ce,"[8.6705, 56.383]",Point,2024-01-03T07:23:16.018000+00:00,2024-01-03T14:15:17.652069+00:00,2024-01-02T00:00:00.001000+01:00,bright_sunshine,manual,06056,day,2024-01-03T00:00:00+01:00,True,0.0,24.0,NaN,NaN,NaN
4,Feature,009a06ea-531d-2993-c75c-d83cdae9a92e,"[-52.6961, 70.7342]",Point,2024-01-02T00:50:30.853006+00:00,2025-05-16T10:24:49.602916+00:00,2024-01-01T23:00:00+00:00,max_wind_speed_3sec,manual,04213,hour,2024-01-02T00:00:00+00:00,True,9.5,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29390,Feature,fe3786ea-eb14-a9a3-186f-a45b836d5cfb,"[-37.6367, 65.6111]",Point,2024-01-01T01:51:23.545286+00:00,2024-01-02T13:21:56.037519+00:00,2024-01-01T00:00:00+00:00,mean_radiation,manual,04360,hour,2024-01-01T01:00:00+00:00,True,0.0,NaN,NaN,NaN,NaN
29391,Feature,feb7d1bf-b166-5aaf-11cd-12827997c9b4,"[8.3207, 56.7637]",Point,2024-01-02T15:04:31.810000+00:00,2024-01-03T09:47:17.459215+00:00,2024-01-01T00:00:00+00:00,min_temp,manual,06051,hour,2024-01-01T01:00:00+00:00,True,5.1,NaN,NaN,NaN,NaN
29392,Feature,fedc163e-4573-6d55-e70a-cc8a45b6e596,"[12.3424, 56.1193]",Point,2024-01-02T15:04:36.893000+00:00,2024-01-03T09:47:38.818374+00:00,2024-01-01T00:00:00+00:00,mean_pressure,manual,06168,hour,2024-01-01T01:00:00+00:00,True,1001.0,NaN,NaN,NaN,NaN
29393,Feature,ff472913-b6f4-5f1f-093a-43ef445ab00e,"[-42.0678, 61.9364]",Point,2024-01-01T01:51:23.545286+00:00,2025-05-16T10:23:53.225943+00:00,2024-01-01T00:00:00+00:00,mean_wind_dir,manual,04382,hour,2024-01-01T01:00:00+00:00,True,347.0,NaN,NaN,NaN,NaN
29394,Feature,ff87bb11-c642-567b-987d-766635494aeb,"[-56.1306, 72.7903]",Point,2024-01-01T01:50:30.343486+00:00,2025-05-16T10:27:05.706059+00:00,2024-01-01T00:00:00+00:00,max_wind_speed_3sec,manual,04211,hour,2024-01-01T01:00:00+00:00,True,11.1,NaN,NaN,NaN,NaN

### Day ahead prices

In [11]:
day_ahead = pd.read_csv('DayAheadPrices/DayAheadPrices_DK1_202401010000-202501010000.csv')

display(day_ahead)

,MTU (UTC),Area,Sequence,Day-ahead Price (EUR/MWh),Intraday Period (UTC),Intraday Price (EUR/MWh)
0,31/12/2023 23:00:00 - 01/01/2024 00:00:00,BZN|DK1,Without Sequence,16.99,NaN,NaN
1,01/01/2024 00:00:00 - 01/01/2024 01:00:00,BZN|DK1,Without Sequence,28.14,NaN,NaN
2,01/01/2024 01:00:00 - 01/01/2024 02:00:00,BZN|DK1,Without Sequence,26.66,NaN,NaN
3,01/01/2024 02:00:00 - 01/01/2024 03:00:00,BZN|DK1,Without Sequence,4.14,NaN,NaN
4,01/01/2024 03:00:00 - 01/01/2024 04:00:00,BZN|DK1,Without Sequence,-0.03,NaN,NaN
...,...,...,...,...,...,...
8779,31/12/2024 18:00:00 - 31/12/2024 19:00:00,BZN|DK1,Without Sequence,25.02,NaN,NaN
8780,31/12/2024 19:00:00 - 31/12/2024 20:00:00,BZN|DK1,Without Sequence,19.00,NaN,NaN
8781,31/12/2024 20:00:00 - 31/12/2024 21:00:00,BZN|DK1,Without Sequence,15.70,NaN,NaN
8782,31/12/2024 21:00:00 - 31/12/2024 22:00:00,BZN|DK1,Without Sequence,9.06,NaN,NaN
8783,31/12/2024 22:00:00 - 31/12/2024 23:00:00,BZN|DK1,Without Sequence,0.52,NaN,NaN

### Consumption

In [12]:
with zipfile.ZipFile('2024_Consumption.zip') as z:
    # Get the first (and only) file inside the zip
    file_name = z.namelist()[0]

    # Open the file inside the zip and read it with pandas
    with z.open(file_name) as f:
        df = pd.read_csv(f)

display(df)

,TimeUTC,TimeDK,MunicipalityCode,Municipality,RegionName,HousingCategory,HeatingCategory,ConsumptionkWh
0,2023-12-31T23:00:00,2024-01-01T00:00:00,860,Hjørring,Region Nordjylland,Parcel- og rækkehuse,Elvarme eller varmepumpe,5053.475
1,2023-12-31T23:00:00,2024-01-01T00:00:00,860,Hjørring,Region Nordjylland,Parcel- og rækkehuse,Andet,7957.491
2,2023-12-31T23:00:00,2024-01-01T00:00:00,860,Hjørring,Region Nordjylland,Fritidshuse,Elvarme eller varmepumpe,3813.127
3,2023-12-31T23:00:00,2024-01-01T00:00:00,860,Hjørring,Region Nordjylland,Fritidshuse,Andet,218.168
4,2023-12-31T23:00:00,2024-01-01T00:00:00,860,Hjørring,Region Nordjylland,Etageejendom,Elvarme eller varmepumpe,89.426
...,...,...,...,...,...,...,...,...
5699726,2024-12-31T22:00:00,2024-12-31T23:00:00,101,København,Region Hovedstaden,Fritidshuse,Andet,178.665
5699727,2024-12-31T22:00:00,2024-12-31T23:00:00,101,København,Region Hovedstaden,Etageejendom,Elvarme eller varmepumpe,514.990
5699728,2024-12-31T22:00:00,2024-12-31T23:00:00,101,København,Region Hovedstaden,Etageejendom,Andet,42063.577
5699729,2024-12-31T22:00:00,2024-12-31T23:00:00,101,København,Region Hovedstaden,Andet,Elvarme eller varmepumpe,30.190
5699730,2024-12-31T22:00:00,2024-12-31T23:00:00,101,København,Region Hovedstaden,Andet,Andet,2226.807